language: groovy

sudo: false

jdk:
  - oraclejdk7
  
# env:
#   - GRAILS_VERSION=2.5.3
  
# before_install:
#   - rm -rf ~/.gvm
#   - curl -s get.sdkman.io | bash
#   - source "$HOME/.sdkman/bin/sdkman-init.sh"
#   - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
#   - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  # dev null is to avoid the need for user input https://github.com/sdkman/sdkman-cli/issues/101
#   - sdk install grails $GRAILS_VERSION < /dev/null
#   - sdk use grails $GRAILS_VERSION
#   - grails -version
#   - sdk current grails

branches:
  only:
    - master

before_script:
  - chmod +x grailsw

script: ./grailsw refresh-dependencies
     && ./grailsw "test-app -integration"

