title: EHRServer
description: Service-oriented openEHR repository for clinical data with composition commit, query and retrieve capabilities.
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
